import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// 引入radis-ui
import "@radix-ui/themes/styles.css"
import { Theme,ThemePanel } from "@radix-ui/themes";
import TopNav from "./ui/common/topNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dog Book"
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* appearance主题模式 */}
        <Theme appearance="dark">
          {children}
          {/* <ThemePanel/> */}
        </Theme>
      </body>
    </html>
  );
}
